### ISSUE TITLE
missing json file

### ISSUE THREAD

**Issue by headwinds** [ldd/tech-tree-js#3]
I've attempted to run this project but getting a #404 on /json/offsets.json

Can you commit this file to project? Or is it a private config file that we need to create ourselves - if so...what's the structure?

**Comment by headwinds** [comment]
this morning my subconscious tipped me off that I should look in your demo and sure enough I found the missing json and the images I needed to recreate this awesome demo. I've forked it - are you open to pull a request?

[offsets](https://ldd.github.io/tech-tree-js/json/offsets.json)         
[data](https://ldd.github.io/tech-tree-js/json/data.json)     
[settings](https://ldd.github.io/tech-tree-js/json/settings.json)

**Comment by ldd** [comment]
I am very sorry for replying so late, but I've just merged your pull request. 

I was somewhat sick this weekend and I didn't check my github account until now. A thousand thanks for taking the time to include these files. 😄
